name: Automatic rebuild of the db
on: push

jobs:
  run:
    name: Rebuild db
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
			
      - name: Rebuild db
        run: ./mkall
		
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Github Actions
          author_email: actions@github.com
          message: 'Rebuilded Automatically the db'
          add: '*'
