name: OUR .ecmp file check CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libcurl
      run: sudo apt-get install libcurl4-gnutls-dev -y
    - name: configure libspm
      run: git clone https://github.com/Soviet-Linux/libspm && cd libspm && make all && make formats && make test && sudo make install
    - name: Try .ecmp files
      run: ./bin/spm-test install ../testing/src/*.ecmp && ./bin/spm-test install ../lxde/src/*.ecmp && ./bin/spm-test install ../xorg/src/*.ecmp && ./bin/spm-test install ../xfce/src/*.ecmp && ./bin/spm-test install ../kde/src/*.ecmp && ./bin/spm-test install ../base/src/*.ecmp